# 2026-01.yaml
empleador: "NOMBRE EMPLEADOR"
direccion: "DIRECCIÓN"
grupo: "21"
bps: "0000000"
rut: "000000000000"
empleado: "APELLIDO, NOMBRE"
ci: "0000000-0"
fecha_ingreso: "dd/mm/aa"
institucion: "NOMBRE BANCO"
cuenta: "0000000"
tipo_pago: "MENSUAL"
lugar_pago: "MONTEVIDEO"
forma_pago: "Transferencia Bancaria"
### Editar todos los meses a partir de acá
periodo: "Enero 2026"
fecha_pago: "5 de febrero de 2026"
ingresos:
  "Sueldo Básico": 10000.00
  "Salario Vacacional": 3000.00
ingresos_no_deducibles:
  - "Salario Vacacional"
descuentos: # porcentajes
  "Fondo Social SD": 0.00
  "Aporte jubilatorio": 15.00
  "Seguro de enfermedad": 3.00
  "FRL": 0.10
transporte: 510
